export const types = {
    //user register
    USER_REGISTER: "USER_REGISTER",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

    //user login
    USER_LOGIN: "USER_LOGIN",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

    //clear login state
    CLEAR_LOGIN_STATE: "CLEAR_LOGIN_STATE",

    //clear register state
    CLEAR_REGISTER_STATE: "CLEAR_REGISTER_STATE",

    //get match list
    GET_MATCH_LIST: "GET_MATCH_LIST",
    GET_MATCH_LIST_SUCCESS: "GET_MATCH_LIST_SUCCESS",
    GET_MATCH_LIST_FAILURE: "GET_MATCH_LIST_FAILURE",

    //get match details
    GET_MATCH_DETAILS: "GET_MATCH_DETAILS",
    GET_MATCH_DETAILS_SUCCESS: "GET_MATCH_DETAILS_SUCCESS",
    GET_MATCH_DETAILS_FAILURE: "GET_MATCH_DETAILS_FAILURE",

    //create match booking
    CREATE_BOOKING: "CREATE_BOOKING",
    CREATE_BOOKING_SUCCESS: "CREATE_BOOKING_SUCCESS",
    CREATE_BOOKING_FAILURE: "CREATE_BOOKING_FAILURE",

    //clear match state
    CLEAR_MATCH_STATE: "CLEAR_MATCH_STATE",

    //get booking list
    GET_CUSTOMER_BOOKING_LIST: "GET_BOOKING_LIST",
    GET_CUSTOMER_BOOKING_LIST_SUCCESS: "GET_BOOKING_LIST_SUCCESS",
    GET_CUSTOMER_BOOKING_LIST_FAILURE: "GET_BOOKING_LIST_FAILURE",

    //save user poll opinion
    SAVE_USER_POLL_OPINION: "SAVE_USER_POLL_OPINION",
    SAVE_USER_POLL_OPINION_SUCCESS: "SAVE_USER_POLL_OPINION_SUCCESS",
    SAVE_USER_POLL_OPINION_FAILURE: "SAVE_USER_POLL_OPINION_FAILURE",

    //get poll results
    GET_POLL_RESULTS: "GET_POLL_RESULTS",
    GET_POLL_RESULTS_SUCCESS: "GET_POLL_RESULTS_SUCCESS",
    GET_POLL_RESULTS_FAILURE: "GET_POLL_RESULTS_FAILURE",

    //clear poll state
    CLEAR_POLL_STATE: "CLEAR_POLL_STATE",

    //create reminder
    CREATE_REMINDER: "CREATE_REMINDER",
    CREATE_REMINDER_SUCCESS: "CREATE_REMINDER_SUCCESS",
    CREATE_REMINDER_FAILURE: "CREATE_REMINDER_FAILURE",

    //get reminder list
    GET_REMINDER_LIST: "GET_REMINDER_LIST",
    GET_REMINDER_LIST_SUCCESS: "GET_REMINDER_LIST_SUCCESS",
    GET_REMINDER_LIST_FAILURE: "GET_REMINDER_LIST_FAILURE",

    //logout
    HANDLE_LOGOUT: "HANDLE_LOGOUT"

}